
import WeatherDashboard from "@/Components/WeatherDashBoard.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
    <WeatherDashboard/>
    </>
  );
}
